"""empty message

Revision ID: ebd914ab4f7a
Revises: 
Create Date: 2020-05-10 19:09:32.992434

"""
from alembic import op
import sqlalchemy as sa
import json
from app import db
from models import Volunteer, Street, District

# revision identifiers, used by Alembic.
revision = 'init_data'
down_revision = 'ebd914ab4f7a'
branch_labels = None
depends_on = None


def upgrade():
    # districts = get_json('data/districts.json')
    # streets = get_json('data/streets.json')
    # volunteers = get_json('data/volunteers.json')

    all_objects = []
    with open('data/volunteers.json', encoding='utf8') as volunteers_file:
        volunteers_data = json.load(volunteers_file)
        volunteers = [
            Volunteer(id=int(id_), name=vol['name'], userpic=vol['userpic'], phone=vol['phone'])
            for id_, vol in volunteers_data.items()
        ]
    all_objects.extend(volunteers)

    with open('data/streets.json', encoding='utf8') as streets_file:
        streets_data = json.load(streets_file)
        streets = [
            Street(id=int(id_), title=st['title'], volunteers=list(filter(lambda x: x.id in st['volunteer'], volunteers)))
            for id_, st in streets_data.items()
        ]
    all_objects.extend(streets)

    with open('data/districts.json', encoding='utf8') as districts_file:
        districts_data = json.load(districts_file)
        districts = [
            District(id=int(id_), title=ds['title'], streets=list(filter(lambda x: x.id in ds['streets'], streets)))
            for id_, ds in districts_data.items()
        ]
    all_objects.extend(districts)

    db.session.add_all(all_objects)
    db.session.commit()


def get_json(filename):
    with open(filename, encoding='utf8') as f:
        data = json.load(f)
    return data


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    districts = get_json('/data/districts.json')
    # ### end Alembic commands ###
